### PR TITLE
add keyword: wait_until_element_is_enabled

### PR DESCRIPTION
**Pull request by JimRevolutionist**
Dear author
   Sorry, I didn't know how to dev in your repo. So this keyword: wait_until_element_is_enabled has no testing. I wrote it by the way like wait_until_element_is_visible.
   I hope you would like to help me with this pr.
Feature Issue link:
https://github.com/GDATASoftwareAG/robotframework-flaui/issues/94

Thanks

### CODE REVIEW

**Comment by JimRevolutionist** [comment]
Dear author @Nepitwin 
    I added the pr changes into local real site-package of robotframework-flaui 2.0.6

    In the case bellow, I believed that the keyword tested pass.
         A button ${identifier} need nearly 5000ms to wait until it's attribute "IsEnabled" changed to be True:
        Wait Until Element Is Enabled    ${identifier}    retries=10(Defaults value), it's test result was pass
        Wait Until Element Is Enabled    ${identifier}    retries=2 ,  it's test result was failed and raise FlaUiError
image
image

**Comment by Nepitwin** [comment]
For testing implementations you have to do here multiple things:

- You can see that direct robot tests are implemented under ATests folder
- Here you have to implement your keyword as a tests under Element.robot
- For a globalized error handling you have to include your additional keywords asweel into ErrorHandling.robot

All test cases are using the test wpf application
image

To test the new keyword we have to implement an additional button which will be disabled for an amount of time and enable it afterwards. Because currently we have no test element to verifiy if the keywords work like expected.

So the TestApplications Project has to be extended by this gui element.

Code looks good so far. If you want i can include this tests for your in your PR.

**Comment by Nepitwin** [comment]
One thins is missing. Pls update the changelog under Unreleased that an additional keywords is implemented.

**Comment by noubar** [comment]
I can also suggest a better approach to achieve your goal:
Imlement "Element Should Be Enabled" keyword rather than "Wait Until Element Is Enabled"
Because you can handle the waiting with "Wait Until Keyword Succeeds" even better like the given example:
Wait Until Keyword Succeeds  10x  100ms   Element Should Be Enabled  <xpath>
This will give the library more flexibality

**Comment by JimRevolutionist** [comment]
> I can also suggest a better approach to achieve your goal: Imlement "Element Should Be Enabled" keyword rather than "Wait Until Element Is Enabled" Because you can handle the waiting with "Wait Until Keyword Succeeds" even better like the given example: Wait Until Keyword Succeeds 10x 100ms Element Should Be Enabled This will give the library more flexibality

Dear @noubar 
    In my understanding: 
Firstly, we can provide "Element Should Be Enabled" and "Wait Until Element Is Enabled" 2 keywords in the /src/FlaUILibrary/keywords/element.py.
This part will be like below:
image


Secondly, we can define "Wait Until Keyword Succeeds"method(I think "wait_until_element_works" will be better) for other "_wait_until_xxxxxxxxx" function no mater "_wait_until_element_is_enabled" or "_wait_until_element_is_visible" and so on.

This part will be like below:
image

**Comment by noubar** [comment]
I mean one keyword "Element should be enabled" is enough.
The waiting part can handle the robot framework. It is not needed to be implemented in flauilibrary.

In my previous comment the keyword "Wait Until Keyword Succeeds" is robot builtin keyword. you can combine both under robot in your tests directly.
I dont know why do we have wait until elment is visible or wait until elment is hidden those keywords are redundant.

I can help you in implementation if you want to.

**Comment by noubar** [comment]
Here is my help:
Take a look to this pr
https://github.com/GDATASoftwareAG/robotframework-flaui/pull/98

**Pull request closed without merging**
