### PR TITLE
#118 Find All Elements keyword

### PR DESCRIPTION
**Pull request by Nepitwin**

### CODE REVIEW

**Comment by JimRevolutionist** [comment]
@Nepitwin 

does element in @{elements} return from 'Find All Elements' can be used in a python method that to operate what can element directly do. Sample Code like below:

```
FOR    ${element}    IN    @{elements}
    ${IsSelected}  get_is_selected_from_vaue_pattern  ${element}
    Log To Console  state is: ${IsSelected}
END

def get_is_selected_from_vaue_pattern(element)
    pattern = element.Patterns.SelectionItem.Pattern
    return Property._prop_to_bool(pattern.IsSelected) 
```

**Comment by Nepitwin** [comment]
@JimRevolutionist 

You mean that some helper keywords can be implemented grab data by index?

For example

${id}  Get Property From Automation Element  ${element}  <INDEX>  AutomationId
${name}  Get Property From Automation Element  ${element}  <INDEX>  Name
${className}  Get Property From Automation Element  ${element}  <INDEX>  ClassName

Well yeah this would be minimize the amount of keyword data to implement but i do not know what the developer will do with this source code because he must always iterate over the list and decides what to do with the xpaths.

But the keyword could be used yes

Get Property From Automation Element

**Comment by JimRevolutionist** [comment]
@Nepitwin 

I see each element in @{elements} return from 'Find All Elements' is just a class object(AutomationElement which has 4 properties as you defined) in this commit, in other word that each element cannot be a uia object that can directly call method as Flaui you transfered. For example there has @{elements} = [ComboBoxAutomationElement1, ComboBoxAutomationElement2], i cannot directly call ComboBoxAutomationElement1.Expand().  I think the return result in this way is unuseful or nosense.

So i want you to consider the return ways, which one would you like better or maybe you have another better way.
First way is return AutomationElement Class object in your commit, I think 'Get Property From Automation Element' would be Necessary.
Second one is return self._automation.GetDesktop().FindAllByXPath(xpath), 'Get Property From Automation Element' would be Not Necessary.

**Comment by JimRevolutionist** [comment]
> 

okay, i agree with you on design side

**Comment by Nepitwin** [comment]
Thanks @JimRevolutionist ,

but your feedback is legitimate. 

The question is whether you can link the Elegant to the design to get the object and include a method to call any keyword functionality.

This would give the use case you name.

Means something like

${element.Acton(Enum.Action, *args})

With this everything would be given that error handling etc is integrated and you have the benefit to access functionalities directly.

You have then both possibilities the keyword use with the Xpaths or the method.

**Pull request merged**
