### PR TITLE
Add support for getting RangeValue Pattern Properties

### PR DESCRIPTION
**Pull request by GeoGegl**
I needed to get the value of a ProgressBar and it only supports RangeValue, not Value pattern.
This small additions let me get the progress value, minimum & maximum

New properties to get:
RANGEVALUE
RANGEMINIMUM
RANGEMAXIMUM
IS_RANGEVALUE_PATTERN_SUPPORTED

### CODE REVIEW

**Comment by Nepitwin** [comment]
@GeoGegl 

Looks good so far. 

Pypi and pylint has to be fixxed.

************* Module src.FlaUILibrary.flaui.module.property
src\FlaUILibrary\flaui\module\property.py:90:0: C0301: Line too long (122/120) (line-too-long)
src\FlaUILibrary\flaui\module\property.py:316:0: C0303: Trailing whitespace (trailing-whitespace)
src\FlaUILibrary\flaui\module\property.py:321:0: C0303: Trailing whitespace (trailing-whitespace)
-----------------------------------
Your code has been rated at 9.99/10

Can you pls extend to write some tests for this new properties under atests aswell and adjust changelog.md to add new keywords?

**Comment by GeoGegl** [comment]
done, please have a look at it

**Review by Nepitwin — APPROVED** [review]

**Comment by Nepitwin** [comment]
i will merge if all tests are green and ship it out as a new version for pypi.

**Comment by Nepitwin** [comment]
One last robocopy issue on build

C:\projects\robotframework-flaui\atests\Property.robot:405:1 [W] 0506 File has too many lines (405/400) (file-too-long)

**Pull request merged**
